name: Build CTE
on: [push]
jobs:
    build:
        runs-on: windows-latest
        steps:
            #- name: get submodules
            #  run: git submodule update --init --recursive
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
                submodules: true
            - name: ls
              run: ls
            - name: build
              run: msbuild CrashTeamEditor.vcxproj /p:configuration=release