name: Build CTE
on: [push]
jobs:
    build:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
                submodules: true
            - name: Set up MSBuild
              uses: microsoft/setup-msbuild@v2
            - name: Restore Nuget
              run: nuget restore CrashTeamEditor.sln
            - name: build
              run: msbuild CrashTeamEditor.vcxproj /p:configuration=release /p:Platform=x64
            - uses: actions/upload-artifact@v4
              with:
                name: CrashTeamEditor
                path: x64\release\
                if-no-files-found: error