name: Build CTE
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            #- name: get submodules
            #  run: git submodule update --init --recursive
            - name: build
              run: msbuild CrashTeamEditor.vcxproj /p:configuration=release